### PR TITLE
Xqiu 20171025 fix janitor updating with outdated status

### PR DESCRIPTION
**Pull request by unieagle**
Fixing issue https://github.com/killbill/killbill/issues/809

@sbrossie @pierre @andrenpaes please review, thanks!

### CODE REVIEW

**Comment by unieagle** [comment]
the `mvn test` are good in my local env and the errors in the ci failure seems not related to this change.

```
Results :

Tests run: 83, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.417 s
[INFO] Finished at: 2017-10-26T11:03:24-07:00
[INFO] Final Memory: 25M/305M
[INFO] ------------------------------------------------------------------------
```

**Comment by unieagle** [comment]
the `mvn test` passed in my local env, seems the ci failures are not related to this change.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] killbill ........................................... SUCCESS [  0.185 s]
[INFO] killbill-api ....................................... SUCCESS [  1.474 s]
[INFO] killbill-util ...................................... SUCCESS [ 26.400 s]
[INFO] killbill-tenant .................................... SUCCESS [  3.935 s]
[INFO] killbill-account ................................... SUCCESS [  7.825 s]
[INFO] killbill-catalog ................................... SUCCESS [ 17.155 s]
[INFO] killbill-currency .................................. SUCCESS [  0.936 s]
[INFO] killbill-subscription .............................. SUCCESS [ 30.938 s]
[INFO] killbill-entitlement ............................... SUCCESS [ 10.219 s]
[INFO] killbill-usage ..................................... SUCCESS [  2.003 s]
[INFO] killbill-invoice ................................... SUCCESS [ 14.911 s]
[INFO] killbill-junction .................................. SUCCESS [  7.590 s]
[INFO] killbill-overdue ................................... SUCCESS [  7.178 s]
[INFO] killbill-payment ................................... SUCCESS [ 15.684 s]
[INFO] killbill-beatrix ................................... SUCCESS [  5.706 s]
[INFO] killbill-jaxrs ..................................... SUCCESS [  8.749 s]
[INFO] killbill-profiles .................................. SUCCESS [  0.002 s]
[INFO] killbill-profiles-killbill ......................... SUCCESS [  7.696 s]
[INFO] killbill-profiles-killpay .......................... SUCCESS [  0.772 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:49 min
[INFO] Finished at: 2017-10-26T11:22:40-07:00
[INFO] Final Memory: 34M/433M
[INFO] ------------------------------------------------------------------------
```

**Comment by pierre** [comment]
> the `mvn test` passed in my local env

Note that this is not enough to run the full regression suite, you need to run `mvn test -Pmysql` instead.

**Comment by unieagle** [comment]
Got it. This is the result of `mvn test -Pmysql`

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] killbill ........................................... SUCCESS [  0.292 s]
[INFO] killbill-api ....................................... SUCCESS [  0.490 s]
[INFO] killbill-util ...................................... SUCCESS [01:03 min]
[INFO] killbill-tenant .................................... SUCCESS [ 15.279 s]
[INFO] killbill-account ................................... SUCCESS [ 16.670 s]
[INFO] killbill-catalog ................................... SUCCESS [ 25.034 s]
[INFO] killbill-currency .................................. SUCCESS [  0.073 s]
[INFO] killbill-subscription .............................. SUCCESS [01:51 min]
[INFO] killbill-entitlement ............................... SUCCESS [01:52 min]
[INFO] killbill-usage ..................................... SUCCESS [ 13.960 s]
[INFO] killbill-invoice ................................... SUCCESS [ 31.283 s]
[INFO] killbill-junction .................................. SUCCESS [01:17 min]
[INFO] killbill-overdue ................................... SUCCESS [ 15.543 s]
[INFO] killbill-payment ................................... SUCCESS [01:07 min]
[INFO] killbill-beatrix ................................... SUCCESS [12:00 min]
[INFO] killbill-jaxrs ..................................... SUCCESS [  5.309 s]
[INFO] killbill-profiles .................................. SUCCESS [  0.003 s]
[INFO] killbill-profiles-killbill ......................... SUCCESS [09:39 min]
[INFO] killbill-profiles-killpay .......................... SUCCESS [  0.092 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30:57 min
[INFO] Finished at: 2017-10-27T10:12:11-07:00
[INFO] Final Memory: 79M/411M
[INFO] ------------------------------------------------------------------------
```
@pierre

**Comment by sbrossie** [comment]
@unieagle I think refreshing the state of the transaction right after taking the lock makes sense, so i am 👍  to merge the PR. 

However, i don't believe this is necessarily enough to solve the issue you described in #809.

@pierre Any objection to merge?

**Comment by unieagle** [comment]
Thanks!
But why is not enough for fixing that issue? What else do you see is needed for fully fixing that?

**Pull request merged**
