### PR TITLE
Work for release 0.23.x promotion

### PR DESCRIPTION
**Pull request by pierre**
Fix merge conflicts.

### CODE REVIEW

**Comment by sbrossie** [comment]
@pierre The reason why the test `TestDefaultEntitlementApi#testCreateBaseWithDifferentStartDate` fails is because we have changed this behavior [here](https://github.com/killbill/killbill/commit/4b32961271d7553d25f4db27e48fa94e7729235d#diff-c4b5e59c2cde4f93acd9024a1dc86b895e246cdd8140752ced39ad6ae39d6450R361): We now realign the provided date if necessary and so the test assertion which only exist in `0.23.x` fails.

**Comment by pierre** [comment]
I actually think my merge missed a hunk from master (specifically https://github.com/killbill/killbill/commit/7ec2a02332667f83bee1005e6deee076896f68a9).

**Comment by sbrossie** [comment]
> I actually think my merge missed a hunk from master (specifically [7ec2a02](https://github.com/killbill/killbill/commit/7ec2a02332667f83bee1005e6deee076896f68a9)).

Yep that makes sense - that's what I would I removed anyways with the new behavior

**Comment by sbrossie** [comment]
\cc  @reshmabidikar I ported the test you had introduced in master in this [commit](https://github.com/killbill/killbill/pull/1742/commits/e134751f7b22aaa4cd1af5e7b15fdc911c889d03)

@pierre I think we are good to merge?

**Review by sbrossie — APPROVED** [review]

**Comment by pierre** [comment]
> @pierre I think we are good to merge?

`test_mixed_catalog_with_usage` is constantly failing though, do you know if it's expected?

**Comment by sbrossie** [comment]
> `test_mixed_catalog_with_usage` is constantly failing though, do you know if it's expected?

I checked and everything got merged from [killbill-integration-tests](ttps://github.com/killbill/killbill-integration-tests); I ran the tests locally multiple times, and they passed for me 🤔

**Pull request merged**
