### PR TITLE
Make record_id columns the bigint type in Postgres

### PR DESCRIPTION
**Pull request by msqr**
In MySQL the record_id columns are created as type `serial` which is a 64-bit integer, but `serial` in Postgres is a 32-bit integer (the `bigserial` type is 64-bit). Add an event trigger function that alters `serial` columns to the `bigint` type after a `CREATE TABLE` DDL event.

### CODE REVIEW

**Comment by sbrossie** [comment]
@msqr It looks like back magic to me, so on my side, the deciding factor will be whether or not our tests pass.

I checked-in your code and tried to run our `postgreSQL` tests:  `mvn test -Ppostgresql` but first test fail, so something is off. 

An easy way to reproduce the issue, if you don't want to tun the whole suite:
```
> cd util
> mvn test -Ppostgresql -Dtest=TestValidationManager

Tests run: 7, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 3.682 sec <<< FAILURE!
beforeSuite(org.killbill.billing.util.validation.TestValidationManager)  Time elapsed: 3.608 sec  <<< FAILURE!
java.io.IOException: org.postgresql.util.PSQLException: ERROR: type "datetime" does not exist
  Position: 850
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:406)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:398)
	at org.killbill.commons.embeddeddb.EmbeddedDB.execute(EmbeddedDB.java:195)
	at org.killbill.commons.embeddeddb.EmbeddedDB.execute(EmbeddedDB.java:186)
	at org.killbill.commons.embeddeddb.EmbeddedDB.executeScript(EmbeddedDB.java:164)
	at org.killbill.billing.DBTestingHelper.executePostStartupScripts(DBTestingHelper.java:78)
	at org.killbill.billing.platform.test.PlatformDBTestingHelper.start(PlatformDBTestingHelper.java:120)
	at org.killbill.billing.GuicyKillbillTestSuiteWithEmbeddedDB.beforeSuite(GuicyKillbillTestSuiteWithEmbeddedDB.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:126)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)


```

**Comment by msqr** [comment]
@sbrossie I am unable to get the tests to compile locally in the 19.x branch; additionally I don't have a Postgres instance available on the default port of `5432`... so if I can overcome these issues I can try to replicate what you're seeing.

Off the top of my head, however, I wonder if it is a version issue: the event trigger features I used were introduced in Postgres 9.5 (and I'm testing in version 9.6). Are you using at least that version?

**Comment by sbrossie** [comment]
On Mon, Sep 25, 2017 at 8:13 PM, Matt Magoffin <notifications@github.com>
wrote:

> @sbrossie <https://github.com/sbrossie> I am unable to get the tests to
> compile locally in the 19.x branch;
>
Yeah, building 19.x  requires building other dependency branches
(killbill-oss-parent, killbill-api, killbill-client, killbill-platform,
killbill-plugin-api).

An easy workaround would be to apply your fix against master-- which does
not require any dependencies to be built.


> additionally I don't have a Postgres instance available on the default
> port of 5432... so if I can overcome these issues I can try to replicate
> what you're seeing.
>
> You should not need any setup.. Tests use an embeded version of potsgres


> Off the top of my head, however, I wonder if it is a version issue: the
> event trigger features I used were introduced in Postgres 9.5 (and I'm
> testing in version 9.6). Are you using at least that version?
>


When logging to our embedded version i see:

psql (9.6.3, server 9.3.5)
​

So looks like our version might be too old?

**Comment by msqr** [comment]
Ah yes, version 9.5 is the minimum required version for my fix to work. I don't think it would be possible to create a fix like this in an earlier version, the `pg_event_trigger_ddl_commands` function was [added in 9.5](https://www.postgresql.org/docs/9.5/static/functions-event-triggers.html). Is it feasible to bump the embedded Postgres version?

**Comment by sbrossie** [comment]
@msqr I update our embedded Postgres Db to `9.6.3`, but i ma still getting the issue:

```
2017-09-28T00:45:00.026+0000 [main] INFO org.killbill.billing.platform.test.PlatformDBTestingHelper - Using PostgreSQL as the embedded database
2017-09-28T00:45:00.552+0000 [main] INFO org.killbill.commons.embeddeddb.postgresql.KillBillEmbeddedPostgreSql - postgres (PostgreSQL) 9.6.3
2017-09-28T00:45:01.714+0000 [main] INFO org.killbill.commons.embeddeddb.postgresql.KillBillEmbeddedPostgreSql - postmaster started on port 60721. Waiting up to 10.00s for startup to finish.
LOG:  database system was shut down at 2017-09-27 17:45:01 PDT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
2017-09-28T00:45:02.039+0000 [main] INFO org.killbill.commons.embeddeddb.postgresql.KillBillTestingPostgreSqlServer - PostgreSQL server ready: jdbc:postgresql://localhost:60721/database988133ae?user=user05991461
2017-09-28T00:45:02.039+0000 [main] INFO org.killbill.commons.embeddeddb.EmbeddedDB - PostgreSQL started: psql -Uuser05991461 -p60721 database988133ae
ERROR:  function update_serial_to_bigint_oncreate() does not exist
STATEMENT:  
	
	CREATE EVENT TRIGGER update_serial_to_bigint_oncreate
	   ON ddl_command_end WHEN TAG IN ('CREATE TABLE')
	   EXECUTE PROCEDURE update_serial_to_bigint_oncreate()
ERROR:  type "datetime" does not exist at character 850
STATEMENT:  CREATE TABLE accounts (
	    record_id serial unique,
	    id varchar(36) NOT NULL,
	    external_key varchar(128) NULL,
	    email varchar(128) NOT NULL,
...
```

**Comment by msqr** [comment]
Oh I'm sorry! I had a typo in there from a last minute name change. I've run this script on a new 9.6 database and verified that it does complete now.

**Comment by sbrossie** [comment]
Looking way better 🎉

**Pull request merged**
