### PR TITLE
usage support proration

### PR DESCRIPTION
**Pull request by wishma2013**
usage support proration in billingPeriod:MONTHLY & usageType:CONSUMABLE & tierBlockPolicy:ALL_TIERS

### CODE REVIEW

**Comment by sbrossie** [comment]
@wishma2013 We typically don't accept feature PR without first discussing the use case. Could you please provide a detailed description of the use case you are trying to solve?

**Comment by wishma2013** [comment]
> @wishma2013 We typically don't accept feature PR without first discussing the use case. Could you please provide a detailed description of the use case you are trying to solve?

Ok.When occur some usage of a subscripted BASE plan, sometimes the BASE plan billing is RECURRING in MONTH, and so is the usage.That is if BASE plan was not subscripted at the billing day, the attendant usage charging will only count the period from subscribe day to next billing day, because the usage we supply to customer is for the whole billing month.That's what we are facing in our business.

**Comment by sbrossie** [comment]
@wishma2013 Unfortunately I am not following the use case: If you could provide something more detailed, e.g with specific dates, how you record your usage points, etc... and highlight the issue based on the scenario that would be useful.

Also prior any PR merge 
* There are lots of conflicting files that need to be resolved
* You are touching some sensitive pieces of code, and yet there is no additional test cases for it -- this needs to be added
* All our regression tests (at least `mvn test -Pmysql` would need to run without error)

**Comment by sbrossie** [comment]
Closing as I don't have enough context on what this PR is supposed to address - see https://github.com/killbill/killbill/pull/1545#issuecomment-998341981

**Pull request closed without merging**
