### PR TITLE
1615 replace guava eventbus with util eventbus

### PR DESCRIPTION
**Pull request by xsalefter**
- replace `Subscribe` and `AllowConcurrentEvents`
- remove guava dependency in several modules.

### CODE REVIEW

**Review by pierre — APPROVED** [review]
I've restarted the build - hopefully, just flakiness 🤞

**Comment by xsalefter** [comment]
Seems like there's 2 problems:

1. `TestUsageInArrear.testWithUsageAtCancellationDayWithUncancel  Time elapsed: 2.654 s  <<< FAILURE!
java.lang.AssertionError: 
Failed to find invoice item type = USAGE and startDate = 2012-04-01, amount = 5.90, endDate = 2012-05-01 for invoice id 4fa5e098-8261-4e23-92e8-273996a31c7a` . Experiencing this locally. But [should be fixed by hard-coded up-to-date](https://github.com/killbill/killbill/pull/1743/commits/11b229f1b49e859d46a823f734292d41c8eedfa2#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R65) commons `killbill-utils`. Let me re-check this later.

2. `Your RubyGems version (2.7.3) has a bug that prevents 'required_ruby_version' from working for Bundler. Any scripts that use 'gem install bundler' will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running 'gem update --system 3.2.3' ` should this a problem, too?

**Comment by pierre** [comment]
For 2., Ruby 2.5.0 matches the version used in the repo (https://github.com/killbill/killbill-integration-tests/blob/work-for-release-0.23.x/.github/workflows/ci.yml). We should definitively upgrade this at some point, I'm just not sure if it's possible to do so right now without code changes.

**Comment by xsalefter** [comment]
Seems like failed in `TestUsageInArrear.testWithUsageAtCancellationDayWithUncancel()` is flakiness: 1st attempt having 2 failed tests, but the 2nd attempt only have 1 failed test with RubyGems version problem. 

>  We should definitively upgrade this at some point, I'm just not sure if it's possible to do so right now without code changes.

Do you mean that we should update ruby version in `ci.yml` in both `killbill` and `killbill-integration-tests` repositories?

**Review by sbrossie — APPROVED** [review]

**Pull request merged**
