### PR TITLE
Avoid NPE with Status#fromStatusCode

### LINKED ISSUE #316: Response.Status 408(Request Timeout) does not exist in jersey core 1.18.1 -> IllegalArgumentException
During updateSubscription (triggered by KillBillJavaClient) server throws TimeoutException while processing SubscriptionResource$EntitlementCallCompletion.withSynchronization. TimeoutException is catched by this method  but javax.ws.rs.core.Response.Status.fromStatusCode(408) returns NULL, because 408 is not yet implemented by jersey-core 1.18.1
So Response.status throws IllegalArgumentException if status is null!

http://docs.oracle.com/javaee/6/api/javax/ws/rs/core/Response.Status.html: 408 is not integrated
http://docs.oracle.com/javaee/7/api/javax/ws/rs/core/Response.Status.html: 408 is integrated

When we recieve the timeout:
If timeout field, in the the client method (updateSubscription), is set to 0, all works fine -> no timeout exception. 
If timeout field, in the the client method (updateSubscription), is set to >=8, all works fine -> no timeout exception. 
If timeout field, in the the client method (updateSubscription), is set  to values between, timeout exception is thrown. 
I have no idea whats wrong with this behaviour, but this is not the point, the problem is that status 408 is not supported by jersey core even if the TimeoutException is raised.

We use killbill server 0.13.6 and java client 0.3.1.

timout

### PR DESCRIPTION
**Pull request by lstephen**
Fixes #316

### CODE REVIEW

**Comment by sbrossie** [comment]
It would be great to have a regression test so we don't have to run manual regression on our side.

**Comment by lstephen** [comment]
Is there any current test covering the class change here, or should I be creating a new test for SubscriptionResource?

**Comment by pierre** [comment]
We do already have some tests [here](https://github.com/killbill/killbill/blob/master/profiles/killbill/src/test/java/org/killbill/billing/jaxrs/TestEntitlement.java).

**Comment by pierre** [comment]
@lstephen Any update?

**Comment by lstephen** [comment]
Sorry, I haven't had a chance to look at adding a test case that covers this.

**Comment by pierre** [comment]
No worries, let us know when you get back to it and if you need some help.

**Pull request merged**
